server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://124.223.15.205:33306/dome?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    password: eXfkpHhY5HFAvp9G
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver